### ISSUE TITLE
default response  missing  content-type header 

### ISSUE THREAD

**Issue by tablecell** [ch1c0t/hobby#6]
test.ru
```ruby
require 'hobby'

class C
  include Hobby

  get "/hello" do
    "Hello, world."
  end
end

#Then, you can create an instance of C with

run C.new

```
rackup test.ru
curl -v  http://localhost:9292/hello
···
< HTTP/1.1 200 OK
< Content-Length: 13
< Server: WEBrick/1.3.1 (Ruby/2.2.2/2015-04-13)
< Date: Thu, 14 Oct 2021 03:17:40 GMT
< Connection: Keep-Alive
<
···

**Comment by ch1c0t** [comment]
Thank you for reporting this. I shall update the readme, at least.

I am not sure yet which [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) should we choose as a default for Hobby. Maybe just require users to set it in their applications?

You can set the content type as follows:

```ruby
class C
  include Hobby

  use Rack::ContentType, 'text/plain'

  get "/hello" do
    "Hello, world."
  end
end
```
